---
title: "Prediction assignment"
author: "p sai praneeth"
date: "10/18/2020"
output:
  html_document: default
  pdf_document: default
---

```{r}
library(caret)
library(rpart)
library(rpart.plot)
library(RColorBrewer)
library(rattle)
library(randomForest)
library(e1071)
library(gbm)
```

##  Introduction of the project

# Data given

The training data : https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv

The test data : https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv

The data for this project come from this source: http://groupware.les.inf.puc-rio.br/har. If you use the document you create for this class for any purpose please cite them as they have been very generous in allowing their data to be used for this kind of assignment.



```{r}
set.seed(12345)
datatrainsite <- "http://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv"
datatestsite<- "http://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv"
datatrain <- read.csv(url(trainUrl), na.strings=c("NA","#DIV/0!",""))
datatest <- read.csv(url(testUrl), na.strings=c("NA","#DIV/0!",""))
```



```{r}
iT <- createDataPartition(training$classe, p=0.6, list=FALSE)
mTr <- datatrain[iT, ]
mTe <- datatrain[-iT, ]
dim(mTr); dim(mTe)
```


```{r}
nzv1 <- nearZeroVar(mTr, saveMetrics=TRUE)
myTraining <- mTr[,nzv1$nzv==FALSE]
nzv1<- nearZeroVar(mTe,saveMetrics=TRUE)
mTe<- mTe[,nzv1$nzv1==FALSE]
```


```{r}
mTr <- mTr[c(-1)]
```


```{r}
trV <- mTr
for(i in 1:length(mTr)) {
    if( sum( is.na( mTr[, i] ) ) /nrow(mTr) >= .7) {
        for(j in 1:length(trV)) {
            if( length( grep(names(mTr[i]), names(trV)[j]) ) == 1)  {
                trV <- trV[ , -j]
            }   
        } 
    }
}

mTr <- trV
rm(trV)
```

```{r}
tclean1 <- colnames(mTr)
tclean2 <- colnames(mTr[, -58])  
mTe <- mTe[tclean1]        
testing <- testing[clean2]             
dim(mTe)
```

```{r}
dim(testing)
```



```{r}
for (i in 1:length(testing) ) {
    for(j in 1:length(mTr)) {
        if( length( grep(names(mTr[i]), names(testing)[j]) ) == 1)  {
            class(testing[j]) <- class(mTr[i])
        }      
    }      
}

testing <- rbind(mTr[2, -58] , testing)
testing <- testing[-1,]
```



```{r}
set.seed(12345)
modFitA1 <- rpart(classe ~ ., data=mTr, method="class")
fancyRpartPlot(modFitA1)
```

```{r}
predictionsA1 <- predict(modFitA1, mTe, type = "class")
cmtree <- confusionMatrix(predictionsA1, mTe$classe)
cmtree
```

```{r}
plot(cmtree$table, col = cmtree$byClass, main = paste("Decision Tree Confusion Matrix: Accuracy =", round(cmtree$overall['Accuracy'], 4)))
```



```{r}
set.seed(12345)
modFitB1 <- randomForest(classe ~ ., data=mTr)
predictionB1 <- predict(modFitB1, mTe, type = "class")
cmrf <- confusionMatrix(predictionB1, mTe$classe)
cmrf
```

```{r}
plot(modFitB1)
```

```{r}
plot(cmrf$table, col = cmtree$byClass, main = paste("Random Forest Confusion Matrix: Accuracy =", round(cmrf$overall['Accuracy'], 4)))
```



```{r}
set.seed(12345)
fitControl <- trainControl(method = "repeatedcv",
                           number = 5,
                           repeats = 1)
tgbmFit1 <- train(classe ~ ., data=mTr, method = "gbm",
                 trControl = fitControl,
                 verbose = FALSE)
tgbmFinMod1 <- gbmFit1$finalModel
tgbmPredTest <- predict(gbmFit1, newdata=mTe)
tgbmAccTest <- confusionMatrix(gbmPredTest, mTe$classe)
tgbmAccTest
```

```{r}
plot(gbmFit1, ylim = c(0.9,1))
```


```{r}
tpredc<- predict(modFitB1, testing, type = "class")
tpredc
```
